// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocdutfpdbvhsrhkvkdwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jZHV0ZnBkYnZoc3Joa3ZrZHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjgzNTEsImV4cCI6MjA3NDAwNDM1MX0.7Zij3IkeSZIxE1FU0eMmZtsWdNvZNbsfOSXH5T4rB7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});